package com.ejemplo;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;

import java.io.IOException;
import java.io.PrintWriter;

@WebServlet("/user-menu-helados")
public class MenuHeladosUserServlet extends HttpServlet {
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        HttpSession session = req.getSession(false);
        String username = (session != null) ? (String) session.getAttribute("username") : "Invitado";

        resp.setContentType("text/html");
        PrintWriter out = resp.getWriter();

        out.println("<!DOCTYPE html>");
        out.println("<html lang='es'>");
        out.println("<head>");
        out.println("    <meta charset='UTF-8'>");
        out.println("    <title>Menú de Helados</title>");
        out.println("    <style>");
        out.println("        body {");
        out.println("            margin: 0;");
        out.println("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;");
        out.println("            background: #f0f0f0;");
        out.println("        }");
        out.println("        header {");
        out.println("            background-color: #6A5ACD;");
        out.println("            color: white;");
        out.println("            padding: 30px;");
        out.println("            text-align: center;");
        out.println("        }");
        out.println("        header a {");
        out.println("            color: #ffdd57;");
        out.println("            text-decoration: none;");
        out.println("            font-weight: bold;");
        out.println("        }");
        out.println("        .contenedor-menu {");
        out.println("            display: grid;");
        out.println("            grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));");
        out.println("            gap: 30px;");
        out.println("            padding: 40px;");
        out.println("            max-width: 1200px;");
        out.println("            margin: auto;");
        out.println("        }");
        out.println("        .producto {");
        out.println("            background: white;");
        out.println("            border-radius: 15px;");
        out.println("            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);");
        out.println("            overflow: hidden;");
        out.println("            transition: transform 0.3s;");
        out.println("        }");
        out.println("        .producto:hover {");
        out.println("            transform: scale(1.03);");
        out.println("        }");
        out.println("        .producto img {");
        out.println("            width: 100%%;");
        out.println("            height: 220px;");
        out.println("            object-fit: cover;");
        out.println("        }");
        out.println("        .producto .info {");
        out.println("            padding: 20px;");
        out.println("        }");
        out.println("        .producto h4 {");
        out.println("            margin-top: 0;");
        out.println("            color: #333;");
        out.println("        }");
        out.println("        .producto p {");
        out.println("            font-size: 14px;");
        out.println("            color: #666;");
        out.println("        }");
        out.println("        .producto ul {");
        out.println("            padding: 0;");
        out.println("            list-style: none;");
        out.println("            margin: 10px 0;");
        out.println("        }");
        out.println("        .producto li {");
        out.println("            margin: 5px 0;");
        out.println("        }");
        out.println("        .producto a {");
        out.println("            display: inline-block;");
        out.println("            margin-top: 10px;");
        out.println("            padding: 10px 20px;");
        out.println("            background: #6A5ACD;");
        out.println("            color: white;");
        out.println("            border-radius: 8px;");
        out.println("            text-decoration: none;");
        out.println("            transition: background 0.3s;");
        out.println("        }");
        out.println("        .producto a:hover {");
        out.println("            background: #5a4acb;");
        out.println("        }");
        out.println("    </style>");
        out.println("</head>");
        out.println("<body>");
        out.println("    <header>");
        out.println("        <h2>¡Hola, " + username + "! Descubre tu sabor favorito</h2>");
        out.println("        <p>Explora nuestra variedad de helados, toppings y tamaños. ¡Hay uno perfecto para ti!</p>");
        out.println("        <a href='index.html'>Volver a inicio</a>");
        out.println("    </header>");
        out.println("    <section class='contenedor-menu'>");

        out.println("        <div class='producto'>");
        out.println("            <img src='img/img1.jpg' alt='Helado en vaso'>");
        out.println("            <div class='info'>");
        out.println("                <h4>Helado en vaso</h4>");
        out.println("                <p>Disfruta de nuestro delicioso helado en vaso, combínalo con tus sabores favoritos.</p>");
        out.println("                <ul>");
        out.println("                    <li><strong>Chico:</strong> $40</li>");
        out.println("                    <li><strong>Mediano:</strong> $55</li>");
        out.println("                    <li><strong>Grande:</strong> $70</li>");
        out.println("                </ul>");
        out.println("                <a href='pedir-helado'>Ordene aquí</a>");
        out.println("            </div>");
        out.println("        </div>");

        out.println("        <div class='producto'>");
        out.println("            <img src='img/img2.jpg' alt='Helado en plato'>");
        out.println("            <div class='info'>");
        out.println("                <h4>Helado en plato</h4>");
        out.println("                <p>Helado por rebanadas. Combínalo con tus sabores favoritos y añade toppings.</p>");
        out.println("                <ul>");
        out.println("                    <li><strong>Chico:</strong> $55</li>");
        out.println("                    <li><strong>Mediano:</strong> $65</li>");
        out.println("                    <li><strong>Grande:</strong> $80</li>");
        out.println("                </ul>");
        out.println("                <a href='pedir-helado'>Ordene aquí</a>");
        out.println("            </div>");
        out.println("        </div>");

        out.println("        <div class='producto'>");
        out.println("            <img src='img/img3.jpg' alt='Helado con galletas'>");
        out.println("            <div class='info'>");
        out.println("                <h4>Helado con galletas</h4>");
        out.println("                <p>Helado suave acompañado de crujientes galletas. Ideal para los más golosos.</p>");
        out.println("                <ul>");
        out.println("                    <li><strong>Chico:</strong> $40</li>");
        out.println("                    <li><strong>Mediano:</strong> $55</li>");
        out.println("                    <li><strong>Grande:</strong> $70</li>");
        out.println("                </ul>");
        out.println("                <a href='pedir-helado'>Ordene aquí</a>");
        out.println("            </div>");
        out.println("        </div>");

        out.println("        <div class='producto'>");
        out.println("            <img src='img/img4.jpg' alt='Helado en cono'>");
        out.println("            <div class='info'>");
        out.println("                <h4>Helado en cono</h4>");
        out.println("                <p>El clásico helado en cono crujiente, perfecto para cualquier ocasión.</p>");
        out.println("                <ul>");
        out.println("                    <li><strong>Chico:</strong> $25</li>");
        out.println("                    <li><strong>Mediano:</strong> $35</li>");
        out.println("                    <li><strong>Grande:</strong> $45</li>");
        out.println("                </ul>");
        out.println("                <a href='pedir-helado'>Ordene aquí</a>");
        out.println("            </div>");
        out.println("        </div>");

        out.println("    </section>");
        out.println("</body>");
        out.println("</html>");
    }
}
